/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'bg-gradient-to-r',
    'from-blue-600',
    'from-green-600',
    'from-purple-600',
    'from-orange-600',
    'to-indigo-600',
    'to-teal-600',
    'to-pink-600',
    'to-yellow-600',
    'bg-clip-text',
    'text-transparent',
    'bg-white/80',
    'backdrop-blur-md',
    'rounded-2xl',
    'shadow-lg',
    'border',
    'border-white/20',
    'border-orange-200',
    'border-teal-200',
    'border-purple-200',
    'text-center',
    'mb-10',
    'text-5xl',
    'font-bold',
    'mb-4',
    'text-gray-600',
    'text-xl',
    'space-y-12',
    'text-2xl',
    'text-gray-800',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'gap-6',
    'bg-white/50',
    'backdrop-blur-sm',
    'p-6',
    'rounded-xl',
    'shadow-md',
    'transition-transform',
    'hover:transform',
    'hover:scale-105',
    'hover:shadow-lg',
    'relative',
    'absolute',
    'top-0',
    'right-0',
    'bg-emerald-500',
    'text-white',
    'text-xs',
    'px-2',
    'py-1',
    'rounded-bl-lg',
    'rounded-tr-lg',
    'z-10',
    'flex',
    'items-center',
    'mr-1',
    'bg-amber-500',
    'text-4xl',
    'mb-3',
    'font-semibold',
    'bg-gradient-to-br',
    'from-blue-50',
    'to-indigo-50',
    'min-h-screen',
    'py-10',
    'px-6',
    'max-w-6xl',
    'mx-auto',
    'w-full',
    'h-full',
    'justify-center'
  ],
  mode: 'jit',
  theme: {
    extend: {
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out forwards',
      },
      animationDelay: {
        '150': '150ms',
        '300': '300ms',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        '.animation-delay-150': {
          'animation-delay': '150ms',
        },
        '.animation-delay-300': {
          'animation-delay': '300ms',
        },
      }
      addUtilities(newUtilities)
    }
  ],
}; 